export const LOGIN = 'LOGIN';
export const SEARCH_PLANET_SUCCESS = 'SEARCH_PLANET_SUCCESS';
export const SEARCH_PLANET_FAILURE = 'SEARCH_PLANET_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const SEARCH_PLANET='SEARCH_PLANET';
